### ISSUE TITLE
Mitsuba blender export .xml error 

### ISSUE THREAD

**Issue by alialsahlany** [mitsuba-renderer/mitsuba-blender#107]
I am not able to export a .XML.
I use Blender v4.1
![Captjjjjjjure](https://github.com/mitsuba-renderer/mitsuba-blender/assets/59419628/76fd4907-9aff-4acb-a726-e341de4947d9)

Mitsuba blender
![Uploading 2.PNG…]()

**Comment by bathal1** [comment]
Hi,
It would be very helpful if you could share a minimal blender scene that produces this error.

**Comment by alialsahlany** [comment]
> Hi, It would be very helpful if you could share a minimal blender scene that produces this error. Also, which release of the add-on are you using ?

Thank you. I installed a previous version of Blender 3.6 and Mitsuba 3.4.1,and I have the same problem.
![image](https://github.com/mitsuba-renderer/mitsuba-blender/assets/59419628/2e292958-95f1-4a4a-b231-f6e14cd3b5d2)

**Comment by bathal1** [comment]
Thanks for this information. Unfortunately, I cannot infer much from a screenshot of your scene, can you please share the `.blend` file here ?

**Comment by alialsahlany** [comment]
> Thanks for this information. Unfortunately, I cannot infer much from a screenshot of your scene, can you please share the `.blend` file here ?

mecaa2.blend 

you can download it

**Comment by bathal1** [comment]
Thank you. The error happens because you have linked a diffuse BSDF node to the world output, which is not supported by the exporter as it is ill-defined. It should have logged an error instead of failing, I will fix that shortly.

In the meantime, I suggest you use a [Background](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/background.html) node instead, which is intended for this anyway.

**Comment by alialsahlany** [comment]
> Thank you. The error happens because you have linked a diffuse BSDF node to the world output, which is not supported by the exporter as it is ill-defined. It should have logged an error instead of failing, I will fix that shortly.
> 
> To solve your exporting issue, I suggest you use a [Background](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/background.html) node instead, which is intended for this anyway.

I installed Blender 3.6 and everything is now OK.
