### ISSUE TITLE
Other variants of the compilation are not displayed in Blender

### ISSUE THREAD

**Issue by HuixianZhong** [mitsuba-renderer/mitsuba-blender#117]
**Bug Description**
I need to use other variants in mitsuba3 (like cuda_mono_polarized), which has been compiled and verified to work. However, after specifying the address of the compilation file using the plugin, the console does not show the variants I compiled, but the four default variants (scalar_rgb, scalar_spectral, cuda_ad_rgb, llvm_ad_rgb) in Mitsuba. I didn't even compile the last three variants.

**To Reproduce**
![1](https://github.com/user-attachments/assets/8f80e357-f627-44e6-b60f-e61a5f12d2c0)
<img width="218" alt="2" src="https://github.com/user-attachments/assets/59b1838b-d10f-4758-a61a-e214ceefb5b0">

**Expected behavior**
Hopefully it will show up and implement the functionality of the variant “cuda_mono_polarized” I've compiled.

**Environment (please complete the following information):**
 - OS: [Windows]
 - Blender Version: [4.0]
 - Add-on Version: [0.4.0]
 - mitsuba vision: [3.5.0]

**Comment by bathal1** [comment]
Hi,

It looks like it is still loading the pip-installed version of mitsuba, as seen in the first image "found custom mitsuba 3.5.0". Did you restart blender after setting the path to the local build folder ?

**Comment by HuixianZhong** [comment]
> Hi,
> 
> It looks like it is still loading the pip-installed version of mitsuba, as seen in the first image "found custom mitsuba 3.5.0". Did you restart blender after setting the path to the local build folder ?

Thanks for the reply. 
Unfortunately, I've restarted it several times, but the interface hasn't changed.

**Comment by merlinND** [comment]
Is it possible that your custom-compiled version uses a different Python version than Blender, and so Blender falls back to loading the pip-installed version instead?

**Comment by HuixianZhong** [comment]
> Is it possible that your custom-compiled version uses a different Python version than Blender, and so Blender falls back to loading the pip-installed version instead?

Thanks very much. That's the problem. It has been displayed correctly after modification.
