### ISSUE TITLE
error messsage

### ISSUE THREAD

**Issue by ekswathi** [mitsuba-renderer/mitsuba-blender#23]
![image](https://user-images.githubusercontent.com/51689618/186304904-c8b62688-6759-4030-bc46-146c3dba9112.png)
Please help
same message in win 10, Blender 2.93 and blender 3.2

**Comment by ros-dorian** [comment]
Hello,

This code is part of the renderer integration which is unfortunately still a work in progress and does not currently work. If you want to render your scene using Mitsuba, we encourage you to export it using **File** -> **Export** -> **Mitsuba** and to call Mitsuba's executable on the output file.

Hope this helps!

**Comment by cfreude** [comment]
Is there any news or progress on this? Still getting this error.

**Comment by merlinND** [comment]
Hello @cfreude,

Could you please open a new issue with full details of your setup (software versions, OS), what you are trying to do and which error message you get. Please also make sure that you have the latest version of the add-on installed.
