### ISSUE TITLE
Infer face_normals=True/False according to .use_smooth attribute of polygons

### ISSUE THREAD

**Issue by waytobehigh** [mitsuba-renderer/mitsuba-blender#24]
Hi folks! I believe, it would be really helpful to toggle the export of face/vertex normals naturally by using `Shade smooth` or `Shade flat` options in Blender. It can be inferred via `.use_smooth` property of faces on export stage.

If that makes sense, I can draft a PR.

**Comment by ros-dorian** [comment]
Hello,

The add-on should already support exporting both flat & smooth shaded meshes by setting Mitsuba's `face_normals` flag as you can see below.

https://github.com/mitsuba-renderer/mitsuba-blender/blob/2b9365f3856c5ed8951962e385f1468426a16517/mitsuba-blender/io/exporter/geometry.py#L139-L141

If this does not do what you expect, can you please explain in more details what issue you are experiencing and how to reproduce it ? Also, can you indicate which version of Blender & the add-on you are testing this with ?

Thank you!

**Comment by ros-dorian** [comment]
Which version of Blender are you using? This works with Blender 2.93 but something may have changed in later versions.

**Comment by waytobehigh** [comment]
I am using Blender 2.93 and current master branch for the add-on

**Comment by waytobehigh** [comment]
Oh, I actually double-checked with the sphere and it worked for me too... I did not understand yet why, but worked :)

Never mind, sorry for raising the issue and thank you for looking into that!
