### ISSUE TITLE
Wrong fov for vertical cameras during export

### ISSUE THREAD

**Issue by waytobehigh** [mitsuba-renderer/mitsuba-blender#25]
Hi! I noticed that while exporting scenes with vertical cameras (resy > resx), fov becomes diffenent. Horizontal cameras (resy < resx) are exported perfectly. Please see the examples below.

Fixed that with changing the line below to `params["fov"] = max(b_camera.data.angle_x, b_camera.data.angle_y) * 180 / np.pi` on my end.
https://github.com/mitsuba-renderer/mitsuba-blender/blob/2b9365f3856c5ed8951962e385f1468426a16517/mitsuba-blender/io/exporter/camera.py#L11

[untitled.blend.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/9417236/untitled.blend.zip)
<div class="row">
<img src="https://user-images.githubusercontent.com/33276701/186449506-dc586758-a896-49ac-8bf0-53df994a52e7.png" alt="mitsuba" width="200"/>
<img src="https://user-images.githubusercontent.com/33276701/186449564-dcc7c695-6f2d-4b41-b16d-0f02c93f0011.png" alt="blender" width="200"/>
</div>
Blender is the rightmost and Mitsuba is the leftmost.

**Comment by ros-dorian** [comment]
Thanks for the catch! 

Apparently, Blender has a `sensor_fit` parameter in the camera data structure that defines how the FOV is used by the renderer. The default value is `AUTO` which associate the `angle_x` FOV to the largest image dimension.

**Comment by ros-dorian** [comment]
Let me know if this fixes your issue!

**Comment by waytobehigh** [comment]
Horizontal ones still coincide

**Comment by ros-dorian** [comment]
I'll check again

**Comment by ros-dorian** [comment]
Okay, it should be fixed now!

**Comment by waytobehigh** [comment]
Works great, thank you!
