### ISSUE TITLE
Exporter/Importer: Blender crash on import/export

### ISSUE THREAD

**Issue by Yonkygon** [mitsuba-renderer/mitsuba-blender#36]
I am trying to export or import an xml file and blender closes.

Console output:

```
Read prefs: /home/user/.config/blender/2.93/config/userpref.blend
jit_cuda_init(): could not find symbol "cuDevicePrimaryCtxRelease_v2" -- disabling CUDA backend!
mitsuba-blender v0.1alpha registered (with mitsuba v3.0.1)
Read blend: /home/user/Blender-Projects/dao.blend
Scene File: /home/user/Blender-Projects/dao.xml
Scene Folder: /home/user/Blender-Projects
Writing: /tmp/dao.crash.txt
Segmentation fault (memory stack flushed to disk)
```

 - OS: Ubuntu 22.04.1
 - Blender Version: 2.93.10
 - Add-on Version: latest

**Comment by Yonkygon** [comment]
[dao.crash.txt](https://github.com/mitsuba-renderer/mitsuba-blender/files/9527943/dao.crash.txt)
[dao.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/9527969/dao.zip)
Rendering existing xml files by Mitsuba 3 works well. Blender file has no dependencies, such as textures, etc., or we are talking about other dependencies?

**Comment by bathal1** [comment]
This seems to be the same issue as #81
