### ISSUE TITLE
Installation: Fail to load package after pip install

### ISSUE THREAD

**Issue by Michele1996** [mitsuba-renderer/mitsuba-blender#37]
Hi
I'm encountering problems with the mitsuba2-blender add-on 
It says it fails to install the package but actually I can use mitsuba in the terminal , so it install it
I can also install mitsuba by myself with pip but still not working
I tried a custom version with mitsuba2 but it doesn't work too but, In the scripting window, I can import mitsuba 
Do you have any suggestion to help me solve that problem?
 
It is on in the add-on window that it shows: Fail to load package 
And when I choose to use the custom path it doesn't show anything  (just the checkbox but any near message)
but still I cannot see the export import option

Ubuntu 20.04
Python 3.9.5
Blender 2.93

**Comment by ros-dorian** [comment]
Hello,

Could you please indicate which version (commit or tag) of the add-on you are using? Could you also link some screenshots of the add-on preference panel, any error message that might appear in the console window (you need to launch Blender from the command line to do so), as well as any other information that might help (e.g., list of installed pip packages in your Blender's Python environment)?

Cheers!

**Comment by ros-dorian** [comment]
Closed for inactivity.
