### ISSUE TITLE
Installation: Freeze Python dependencies to predefined versions

### ISSUE THREAD

**Issue by ros-dorian** [mitsuba-renderer/mitsuba-blender#40]
As the Python dependencies of the add-on (`mitsuba` and `drjit`) are evolving, it creates some instabilities if breaking changes are introduced. These issues cannot be caught by the CI because periodic builds are not set up.

**Solution**
We can freeze the version of each dependencies installed by the add-on and make a pull request with the changes required by the newer versions. This avoids random installation failures in the wild, but would constrain the add-on to a specific `mitsuba` version (in the case of custom builds).

**Comment by merlinND** [comment]
How about installing a specific version when the user uses the "install from pip" method, but simply recommend a version number when the user uses a custom build? The compatible version number could be written above the directory input in the settings.

**Comment by ros-dorian** [comment]
Good idea indeed!
