### ISSUE TITLE
Installation: Crash when choosing custom mitsuba path

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba-blender#41]
**Bug Description**
Blender crashes when I switch on the mitsuba-blender addon and add the custom path to mitsuba, which is compiled from the source.
```
free(): invalid pointer
Aborted (core dumped)
```

**To Reproduce**
1. Compile mitsuba [121a637d](https://github.com/mitsuba-renderer/mitsuba3/commit/121a637d78f5288fe9b3e6a6c429b5e5c7ccebe7)) from source. 
2. Switch on the addon from blender -> preferences -> addons
3. Click on `Use custom Mitsuba path`
4. Select the `build` directory 

**Expected behavior**
The plugin to load properly without any crashes

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Blender Version: 3.4.0 Alpha
 - Add-on Version: 9d9a4cb

**Additional context**
The crash also occurs when I install mitsuba using pip.

**Comment by ros-dorian** [comment]
As discussed in #38, the bug comes from Mitsuba 3.0.2 which is the version you are trying to use. I would suggest either waiting for Mitsuba 3.0.3 or using an older version of Mitsuba (tag `v3.0.1`).

**Comment by EsteBran** [comment]
Hello, I built Mitsuba v3.0.1 as outlined in the compile and build instructions, then tried to set the custom mitsuba build path to the Release folder containing `mitsuba.exe` and got the same result. "Failed to load custom Mitsuba. Please verify the path to the build directory."
