### ISSUE TITLE
Importer/Exporter: uv coordinates flipped when importing exported scene.

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/mitsuba-blender#50]
**Bug Description**
When exporting a scene to the mitsuba format and importing it back into blender the vertical axis of the uv map is flipped.

**To Reproduce**
1. Export scene to mitsuba xml
2. Import same scene to blender

**Expected behavior**
UV coordinates should be the same after importing

**Resources**
Before:
![Screenshot from 2022-11-12 00-36-57](https://user-images.githubusercontent.com/23581448/201444554-b6d211ab-4484-4cd4-9f4f-87effa33daa6.png)
After:
![Screenshot from 2022-11-12 00-37-47](https://user-images.githubusercontent.com/23581448/201444600-85641c6c-529b-4d85-a08c-174b30c88148.png)

**Environment:**
 - OS: Linux
 - Blender Version: 3.3
 - Add-on Version: latest

**Comment by ros-dorian** [comment]
Hello,

Good catch! This PR should fix this problem, but I'll let you double-check that it indeed works now.

Cheers!
