### ISSUE TITLE
Exporter: Sequence animations simulations; in blender rendering

### ISSUE THREAD

**Issue by 240db** [mitsuba-renderer/mitsuba-blender#52]
**Feature request: Exporter**
In blender rendering integration or a suggestion/workaround on exporting scene animation sequences.

**Is your feature request related to a problem? Please describe.**

I read the wiki on the exporter module current functionalities' support at 

- https://github.com/mitsuba-renderer/mitsuba-blender/wiki/Exporting-a-Blender-scene

"**Future versions may support more fancy features**, such as custom nodes for materials or **in-blender rendering**."

I'm going to try a few things myself, but I was wondering how could one use Mitsuba render engine directly in Blender? Or use the xml export and export a frame sequence similar to blender command line for animation rendering. Cameras objects would be nice as well. 

**Describe the solution you'd like**

Currently I have a few scenes in Blender, and I use the LuxCore render engine to use the Metropolis method and easily get caustics along boids and ocean simulations. 

 
![orca](https://user-images.githubusercontent.com/28659434/204974525-41d5c23f-c7b1-4072-9c0f-4fd378a69c6d.gif)

I was wondering if I could get this exact project and render the animation sequence, so like a series of images I could later turn into a video... or even pipe ffmpeg to export a video too. 

**Describe alternatives you've considered**

At first I thought of setting a different frame and sequentially export the xml corresponding to the frame, but it would be a lot easier if I could control the xml like the blender command line animation render options, perhaps mitsuba would give even greater control like different/multiple camera selection  

**Additional context**

I was first interested in Mitsuba after reading Tizian Zeltner, Iliyan Georgiev, and Wenzel Jakob. 2020. Specular Manifold Sampling for Rendering High-Frequency Caustics and Glints. In Transactions on Graphics (Proceedings of SIGGRAPH) 39(4). The caustics were quickly calculated, I believe it could beat LuxCore current performance on CPUs. 

This is what I am trying to accomplish with Mitsuba in my pipeline. I used the Metropolis method in LuxCore as a render engine, directly in Blender. I was able to do all sorts of fancy stuff like boids, ocean simulation, multiple cameras... but it takes ages for an animation sequence. 

https://user-images.githubusercontent.com/28659434/204975973-81bd0d8e-d638-4e19-b0c2-dd67c09d4730.mp4

https://user-images.githubusercontent.com/28659434/204975921-56a895b8-1d63-457a-9ae1-b24db6567ff5.mp4

I would be very open to share any potential developments I come up with on trying to implement Mitsuba in my Blender scenes, or help in some other possible way.

**Comment by ros-dorian** [comment]
Hello, thanks for the suggestion!

I believe that Mitsuba 3 does not support animation sequences (see the doc [here](https://mitsuba.readthedocs.io/en/stable/src/key_topics/differences.html#differences-to-mitsuba-0-6)). So describing the animation in the XML scene file is unfortunately not an option.

However, we are working on in-Blender rendering using Mitsuba which should solve your issue.

If you want to try to have a go at it, you can already find the previous (sadly broken) implementation of the renderer in [this](https://github.com/mitsuba-renderer/mitsuba-blender/blob/master/mitsuba-blender/engine/final.py) file.

Cheers!
