### ISSUE TITLE
Exporter: Incorrect PLY geometries when exporting (Blender 3.4+)

### ISSUE THREAD

**Issue by lesterho** [mitsuba-renderer/mitsuba-blender#58]
**Bug Description**
When exporting from Blender to Mitsuba, the resulting ply files produced have different geometries from original Blender files.

**To Reproduce**
For example, I used the following Blender file with 2 planes: 
[Blender2planes.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/11264159/Blender2planes.zip)
![Before export](https://user-images.githubusercontent.com/77397519/232844713-93f4b286-5baa-4e1a-9a14-2c3d55ef7d3a.png)

The exported Mistuba files, with incorrect geometries for the 2 planes:
[Mistuba2planes.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/11264181/Mistuba2planes.zip)
![After export](https://user-images.githubusercontent.com/77397519/232844940-594ed30b-d25b-4e7f-9d78-daaeaea29fa5.png)

**Environment:**
 - OS: Ubuntu 20.04
 - Blender Version: 3.5
 - Add-on Version: latest

**Comment by bathal1** [comment]
There seems to have been breaking changes to the Mesh interface that I haven't had time to investigate yet. However, it seems to still work fine with earlier versions of blender (it works for 3.0 on my end). 

If that's an option for you, I suggest you use an earlier version until we can solve this issue.

**Comment by lesterho** [comment]
It works correctly in Blender 3.0. Many thanks!

**Comment by bathal1** [comment]
I'll leave this open since we want to support more recent versions of blender

**Comment by bathal1** [comment]
I can reproduce this issue with versions of blender 3.4 onwards. This seems to coincide with mesh API changes from blender.
