### ISSUE TITLE
Cannot render in Blender using mitsuba as renderer

### ISSUE THREAD

**Issue by kvuong2711** [mitsuba-renderer/mitsuba-blender#69]
**Issue Title**
When render a simple scene with mitsuba as the renderer, the image is empty.

**Bug Description**

`Traceback (most recent call last):
  File "/home/khiem/.config/blender/3.3/scripts/addons/mitsuba-blender/engine/final.py", line 42, in render
    self.converter.scene_to_dict(depsgraph)
TypeError: SceneConverter.scene_to_dict() missing 1 required positional argument: 'window_manager'
`

**Resources**
Blender file: https://drive.google.com/file/d/1sOkORFJkd8oHzvQwA1Raqm6vMcOON5Z0/view?usp=sharing

**Environment (please complete the following information):**
 - OS: Pop OS 20.04
 - mitsuba-blender v0.1alpha registered (with mitsuba v3.0.1)
 - Blender Version: 3.3.9

**Comment by bathal1** [comment]
Hi,
Rendering with mitsuba within blender is under development, so it is not expected to work for the time being.

**Comment by Spirou4D** [comment]
But how to render a scene, please?
I exported the blend to Mitsuba.xml and re-open with Mitsuba v0.5 but I had the traceback:
[qq](https://www.dropbox.com/scl/fi/uz3q7no5wdlgc8aq9l746/ScreenShot_autres.jpeg?rlkey=b36fpmzfnzjkue2gyu6s32xfq&dl=0)

**Comment by bathal1** [comment]
This is an exporter for Mitsuba 3, not Mitsuba 0.6. See the doces [here](https://mitsuba.readthedocs.io/en/stable/).

**Comment by Spirou4D** [comment]
You don't answer to my question please: How to render this xml file with MITSUBA 3 with blender?
Today you must export your scene in XML file but how to run MITSUBA  with this file please?

**Comment by bathal1** [comment]
1. Install Mitsuba 3 following the docs (using pip is recommended)
2. Export the scene as XML using this addon
3. Render the scene in the command line using `mitsuba <exported_scene_name>.xml`

**Comment by Spirou4D** [comment]
No I have this:
`PS C:\Users\Patrick\Mes Applications\blender-3.3.0-windows-x64\3.3\python\bin> .\python
Python 3.10.2 (main, Jan 27 2022, 08:34:43) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> mitsuba "E:\Users\Patrick\Bureau^untitled.xml"
  File "<stdin>", line 1
    mitsuba "E:\Users\Patrick\Bureau^untitled.xml"
                                                  ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
>>>
`

**Comment by bathal1** [comment]
You seem to be trying to run this command inside a python interactive prompt. If you just want to run `mitsuba`, you need to run it in *the command line*, not inside python.

**Comment by Spirou4D** [comment]
No In command line you must go the folder of MITSUBA3 and type
>.\mitsuba.exe "your file.xml"

**Comment by bathal1** [comment]
How did you install mitsuba 3 ? If you did so using pip, you should be able to use `mitsuba` as I've explained above. If you built it from source, then you will need to run the `setpath.bat` script that will add this folder to your `PATH` environment variable, as explained in the [docs](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html#running-mitsuba).

**Comment by Spirou4D** [comment]
If giving explanations pisses you off, you have to say it right away: I'm going to stop worrying about your damn MITSUBA3, which isn't worth it! Byebye.
