### ISSUE TITLE
Installation: Cannot render an image using render engine 

### ISSUE THREAD

**Issue by chenbixuan2017** [mitsuba-renderer/mitsuba-blender#73]
Hi! I have followed the steos of mitsuba-blender installation in Wiki "Installation & Update Guide": Download the archives "mitsuba-blender.zip", Install Add-on, click on "Install the dependencies with pip"... 
everything looks the same with the captions in the guide.
(It is my first time doing this, so I do not have other versions of the add-on)
Blender version: v3.4

In Blender, when I switched from Cycles to Mitsuba in the Render Engine bar to render an image, no image came out but a chessboard texture, which means nothing was rendered. But everything was okay when using Cycles or other engines like Eevee, etc.

Maybe I need some additional configurations to do, except for the things mentioned in the Wiki guide?
Does anyone know what I should do?
Thanks!

**Comment by bathal1** [comment]
Hi, this is not supported at the moment, see #69

**Comment by chenbixuan2017** [comment]
thank you! I see!
