### ISSUE TITLE
Does not works in Blender 4.0.3

### ISSUE THREAD

**Issue by odil24** [mitsuba-renderer/mitsuba-blender#89]
Just installed from zip and enabled addon also downloaded deps but here whats show:
![0](https://github.com/mitsuba-renderer/mitsuba-blender/assets/64298012/4e0cdd45-ab0f-4cdf-a58e-fb91b50599da)
![01](https://github.com/mitsuba-renderer/mitsuba-blender/assets/64298012/beab63fb-bb50-42f3-83c4-9506fa27d6c6)

I mean it does not show menus and shader editor panel has not

**Comment by bathal1** [comment]
Hi,
What exactly do you mean by "does not work"?  From the screen capture you shared, it looks like the add-on was enabled successfully, as you can see on the right.  The menus shown in (2) are the settings of the Mitsuba integrator, what do you think is missing ?

The lack of shader editor is expected, as there is currently no support for Mitsuba's shading system in the Blender UI. This add-on is primarily design for exporting scenes from Blender to Mitsuba's file format. We do support rendering from the UI directly, which should work in your case if you hit F12.

I suggest you try rendering from the UI using Mitsuba as a render engine, and also try exporting the scene as Mitsuba format, and let us know if that works.

**Comment by bathal1** [comment]
We have just released a new version of the add-on, that should support Blender 4.0. Please upgrade and open another issue if you are unable to use it then.
