### ISSUE TITLE
Failed to export .xml: AttributeError: 'NoneType' object has no attribute 'write_ply'

### ISSUE THREAD

**Issue by zitianlll** [mitsuba-renderer/mitsuba-blender#94]
AttributeError: 'NoneType' object has no attribute 'write_ply'

**Bug Description**
I failed to export a .blend file to .xml file even though I tried different verions of blender and mitsuba-blender. 

**To Reproduce**
1. Go to File
2. Click on Export
3. Scroll down to Mitsuba(.xml)

**Expected behavior**
export .xml successfully

**Resources**
![mitsuba-blender export error](https://github.com/mitsuba-renderer/mitsuba-blender/assets/54493702/d43ca33e-d624-4775-ac36-2a5a06694a53)

**Environment (please complete the following information):**
 - OS: Win11
 - Blender Version: 3.6.9, 3.3.0, 3.6.0, 3.3.9
 - Add-on Version: latest

**Comment by bathal1** [comment]
Hi,
Can you please share a minimal blend file that reproduces this issue so we can look into it ?

**Comment by zitianlll** [comment]
Sure, （＾ｖ＾） 
You can download the blend file [here](https://drive.google.com/file/d/1ayyTny9EVuodGL_98CXuoM4Doo-PGnvy/view?usp=drive_link) .

**Comment by bathal1** [comment]
Thank you for the reproducer. I pushed a fix that should resolve this issue. You can get them by downloading the "Nightly" pre-release on the Releases page.

That said, it seems that you are using some plugin to generate some of the meshes in the scene, which is not supported by the addon. So most of the geometry in the scene will now be ignored. You probably want to convert that geometry to "regular" meshes before exporting.
