### ISSUE TITLE
Importer: Mitsuba object type "SRGBReflectanceSpectrum" is not supported.

### ISSUE THREAD

**Issue by HughieH** [mitsuba-renderer/mitsuba-blender#98]
**Importer: Mitsuba object type "SRGBReflectanceSpectrum" is not supported.**

**Bug Description**
I'm trying to import an example scene from Sionna's Ray Tracing module in ```sionna/rt/scenes/box/box.xml``` in the Sionna library. THe import doesn't work with the error ```Mitsuba object type "SRGBReflectanceSpectrum" is not supported.```.

**To Reproduce**
1. Go to 'https://github.com/NVlabs/sionna'
2. Download the library.
3. Open blender (Blender 3.6.8) with the mitsuba extension (0.3.0).
4. Import the scene from the file path ```sionna/rt/scenes/box/box.xml```
5. See error

**Expected behavior**
Scene should be imported and viewed in Blender GUI.

**Environment (please complete the following information):**
 - OS: MacOS
 - Blender Version: 3.6.8
 - Add-on Version: 0.3.0

**Comment by merlinND** [comment]
Hello,

I haven't tried to reproduce myself, but I am attaching the scene in question for convenience.
[box.zip](https://github.com/mitsuba-renderer/mitsuba-blender/files/15021730/box.zip)

**Comment by HughieH** [comment]
I still have the same issue unfortunately. Could you tell me what version of Blender and Mitsuba-renderer you are using when opening the box.xml file? I made sure to include the meshes in the same directory as well and still run into the problem.

**Comment by HughieH** [comment]
I have also tried importing this scene using Blender 4.0 and Mitsuba-render 0.4.0 with the same result.

**Comment by HughieH** [comment]
I believe it is this element that is causing the import issue in the associated xml file:

```
<emitter type="constant" id="World">
	<rgb value="1.000000 1.000000 1.000000" name="radiance"/>
</emitter>
```
Specifically the rgb values for the radiance tag.
